@extends('app.header')
@section('content')


    @if (Auth::user()->role == 'Super Admin')
        <div class="card p-4 mx-auto">

            <div class="mb-4  d-flex justify-content-between">
                <div class="mb-4  d-flex justify-content-between">Clients</div>

                <div><a href="{{ route('clients.create') }}"
                        class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">Invite</a></div>
            </div>


            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Users</th>
                        <th>Generated URLs</th>
                        <th>Total URL HITs</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($members as $member)
                        <tr>
                            <td>
                                {{ $member->name }}<br>
                                <small>{{ $member->email }}</small>
                            </td>
                            <td>{{ $member->clientmembers->count()  ?? 0 }}</td>
                            <td>{{ $member->clientTotalShortUrls->count()  ?? 0 }}</td>
                            <td>{{ $member->clientTotalShortUrls()->sum('hits')  ?? 0 }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center">No Clients Found.</td>
                        </tr>
                    @endforelse

                </tbody>
            </table>

            <div>
                <a href="{{ route('clients.index') }}"
                    class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">View All</a>
            </div>

        </div>
    @endif



    <div class="card p-4 mx-auto mt-5">
        <div class="mb-4  d-flex justify-content-between">
            <div class="mb-4  d-flex justify-content-between">Generated URLs</div>

            @if(Auth::user()->role != 'Super Admin' && Auth::user()->role != 'Client')
            <div><a href="{{ route('shorturls.create') }}"
                    class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">Generate Url</a></div>
                @endif
            </div>


        <table class="table table-bordered">
            <thead>
                <tr>
                    <th width="20%">Short Url</th>
                    <th width="40%">Longs Url</th>
                    <th width="20%">Generated By</th>
                    <th width="20%">Total URL HITs</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($shortUrls as $shortUrl)
                    <tr>
                        <td>
                            {{route('short-url',[$shortUrl->short_code])}}
                        </td>
                        <td>{{ $shortUrl->long_url }}</td>
                        <td>{{ $shortUrl->user->name ?? ''}}
                            <small>{{ $shortUrl->user->email ?? '' }}</small>
                        </td>
                        <td>{{ $shortUrl->hits }}</td>
                    </tr>
                @empty

                    <tr>
                        <td colspan="4" class="text-center">No Short URLs Generated Yet.</td>
                    </tr>
                @endforelse

            </tbody>
        </table>
         <div>   
                    <a href="{{ route('shorturls.index') }}"
                        class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">View All</a>
                </div>
    </div>




    @if (Auth::user()->role == 'Client' || Auth::user()->role == 'Admin')
        <div class="card mt-5 p-4 mx-auto">

            <div class="mb-4  d-flex justify-content-between">
                <div class="mb-4  d-flex justify-content-between">Team Members</div>

                <div><a href="{{ route('members.create') }}"
                        class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">Invite</a></div>
            </div>


            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>
                        <th>Generated URLs</th>
                        <th>Total URL HITs</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($members as $member)
                        <tr>
                            <td>
                                {{ $member->name }}<br>
                                <small>{{ $member->email }}</small>
                            </td>
                            <td> {{ $member->role ?? '' }}</td>
                            <td>{{ $member->myShortUrls->count()  ?? 0 }}</td>
                            <td>{{ $member->myShortUrls()->sum('hits')  ?? 0 }}</td>
                        </tr>

                    @empty
                        <tr>
                            <td colspan="5" class="text-center">No Members Found.</td>
                        </tr>
                    @endforelse

                </tbody>
            </table>

            <div>
                <a href="{{ route('members.index') }}"
                    class="mx-2 mb-3 text-decoration-none text-success border border-success p-2">View All</a>
            </div>

        </div>
    @endif


@endsection
