@extends('app.header')
@section('content')


    <div class="card p-4 mx-auto mt-5">
        <div class="mb-4  d-flex justify-content-between">Generated URLs</div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th width="20%">Short Url</th>
                    <th width="40%">Longs Url</th>
                    <th width="20%">Generated By</th>
                    <th width="20%">Total URL HITs</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($shortUrls as $shortUrl)
                    <tr>
                        <td>
                            {{route('short-url',[$shortUrl->short_code])}}
                        </td>
                        <td>{{ $shortUrl->long_url }}</td>
                        <td>{{ $shortUrl->user->name ?? ''}}</td>
                        <td>{{ $shortUrl->hits }}</td>
                    </tr>
                @empty

                    <tr>
                        <td colspan="4" class="text-center">No Short URLs Generated Yet.</td>
                    </tr>
                @endforelse

            </tbody>
        </table>
       
    </div>






@endsection
